name: "publish"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./app/src-tauri -> target"

      - name: Install frontend dependencies
        working-directory: ./app
        run: npm install

      - name: Build Tauri portable
        working-directory: ./app
        run: npm run tauri build
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Upload Tauri portable
        uses: actions/upload-artifact@v7
        id: portable
        with:
          name: portable
          path: ./app/src-tauri/target/release/WinScript.exe

      - name: Sign Tauri portable
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORG_ID }}
          project-slug: winscript
          signing-policy-slug: release-signing

          github-artifact-id: ${{ steps.portable.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: signed

      - name: Copy signed portable to build directory
        run: |
          Remove-Item -Path ./app/src-tauri/target/release/WinScript.exe
          cp ./signed/WinScript.exe ./app/src-tauri/target/release

      - name: Build Tauri installer
        working-directory: ./app/src-tauri
        run: npm run tauri bundle -- --bundles nsis
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Rename Tauri installer
        run: |
          Copy-Item "./app/src-tauri/target/release/bundle/nsis/WinScript_*_x64-setup.exe" -Destination "./app/src-tauri/target/release/bundle/nsis/winscript-installer.exe"

      - name: Upload Tauri installer
        id: nsis
        uses: actions/upload-artifact@v7
        with:
          name: installer
          path: ./app/src-tauri/target/release/bundle/nsis/winscript-installer.exe

      - name: Sign Tauri installer
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORG_ID }}
          project-slug: winscript
          signing-policy-slug: release-signing
          artifact-configuration-slug: installer

          github-artifact-id: ${{ steps.nsis.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: signed

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: ./app
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseBody: "*The desktop app may be flagged as a threat by Windows Defender; however, this is a false positive. This occurs because the scripts you create with WinScript can modify system settings. Rest assured, WinScript is safe, transparent, and open-source.*"
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          releaseDraft: true
          prerelease: false
          includeDebug: false
          includeRelease: false
          args: ${{ matrix.args }}

      - name: Wait for release
        run: |
          sleep 5

      - name: Rename signed Tauri portable
        run: |
          Get-Item "signed/WinScript.exe" | Rename-Item -NewName winscript-portable.exe

      - name: Upload signed executables to release
        shell: pwsh
        run: |
          gh release upload ${{ github.ref_name }} signed/* --clobber
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Modify latest.json
        shell: pwsh
        working-directory: ./app
        run: |
          gh release download "${{ github.ref_name }}" -p "latest.json"
          $output = npx tauri signer sign -k "${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}" -p "${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}" "../signed/winscript-installer.exe" 2>&1 | Out-String
          Write-Host $output
          if ($output -match 'Public signature:\s*(?<sig>\S+)') {
              $newSignature = $Matches['sig']
          } else {
              Write-Error "Could not find public signature in output."
          }
          $content = Get-Content -Path "latest.json" -Raw
          $modified = $content -replace 'WinScript_\d+\.\d+\.\d+_x64-setup\.exe', 'winscript-installer.exe'
          $modified = $modified -replace '("signature":\s*")[^"]*(")', "`$1$newSignature`$2"
          $modified | Set-Content -Path "latest.json"
          Get-Content -Path "latest.json"
          gh release upload "${{ github.ref_name }}" "latest.json" --clobber
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Remove signature file
        run: |
          $VERSION = "${{ github.ref_name }}" -replace "^v", ""
          gh release delete-asset "${{ github.ref_name }}" "WinScript_${VERSION}_x64-setup.exe.sig"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
