name: "publish"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./app/src-tauri -> target"

      - name: install frontend dependencies
        working-directory: ./app
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: ./app
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseBody: "*The desktop app may be flagged as a threat by Windows Defender; however, this is a false positive. This occurs because the scripts you create with WinScript can modify system settings. Rest assured, WinScript is safe, transparent, and open-source.*"
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: Wait for release
        run: |
          sleep 5

      - name: Prepare files for SignPath
        shell: pwsh
        run: |
          mkdir release

          ren ./app/src-tauri/target/release/winscript.exe winscript-portable.exe

          copy ./app/src-tauri/target/release/winscript-portable.exe release\
          copy ./app/src-tauri/target/release/bundle/nsis/WinScript_*_x64-setup.exe release\winscript-installer.exe

      - name: Upload unsigned artifact
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: unsigned
          path: release/

      - name: Sign with SignPath
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORG_ID }}
          project-slug: winscript
          signing-policy-slug: test-signing

          github-artifact-id: ${{ steps.upload.outputs.artifact-id }}

          wait-for-completion: true
          output-artifact-directory: signed

      - name: Upload signed executables to release
        shell: pwsh
        run: |
          gh release upload ${{ github.ref_name }} signed/* --clobber
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Modify latest.json
        shell: pwsh
        working-directory: ./app
        run: |
          gh release download "${{ github.ref_name }}" -p "latest.json"
          $output = npx tauri signer sign -k "${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}" -p "${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}" "../signed/winscript-installer.exe" 2>&1 | Out-String
          Write-Host $output
          if ($output -match 'Public signature:\s*(?<sig>\S+)') {
              $newSignature = $Matches['sig']
          } else {
              Write-Error "Could not find public signature in output."
          }
          $content = Get-Content -Path "latest.json" -Raw
          $modified = $content -replace 'WinScript_\d+\.\d+\.\d+_x64-setup\.exe', 'winscript-installer.exe'
          $modified = $modified -replace '("signature":\s*")[^"]*(")', "`$1$newSignature`$2"
          $modified | Set-Content -Path "latest.json"
          Get-Content -Path "latest.json"
          gh release upload "${{ github.ref_name }}" "latest.json" --clobber
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Remove signature file
        run: |
          $VERSION = "${{ github.ref_name }}" -replace "^v", ""
          gh release delete-asset "${{ github.ref_name }}" "WinScript_${VERSION}_x64-setup.exe.sig"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
