name: "publish"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./app/src-tauri -> target"

      - name: Install frontend dependencies
        working-directory: ./app
        run: npm install

      - name: Build Tauri
        working-directory: ./app
        run: npm run tauri build
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
          SIGNPATH_ORG_ID: ${{ secrets.SIGNPATH_ORG_ID }}

      - name: Create Draft release
        run: |
          gh release create ${{ github.ref_name }} --draft --notes "*The desktop app may be flagged as a threat by Windows Defender; however, this is a false positive. This occurs because the scripts you create with WinScript can modify system settings. Rest assured, WinScript is safe, transparent, and open-source.*"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Wait for release
        run: |
          sleep 5

      - name: Rename outputs
        run: |
          Copy-Item "./app/src-tauri/target/release/bundle/nsis/WinScript_*_x64-setup.exe" -Destination "./app/src-tauri/target/release/bundle/nsis/winscript-installer.exe"
          Copy-Item "./app/src-tauri/target/release/WinScript.exe" -Destination "./winscript-portable.exe"

      - name: Upload executables to release
        shell: pwsh
        run: |
          gh release upload ${{ github.ref_name }} `
            "./winscript-portable.exe" `
            "./app/src-tauri/target/release/bundle/nsis/winscript-installer.exe" `
            --clobber
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Create latest.json
        shell: pwsh
        working-directory: ./app
        run: |
          $output = npx tauri signer sign -k "${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}" -p "${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}" "./src-tauri/target/release/bundle/nsis/winscript-installer.exe" 2>&1 | Out-String
          Write-Host $output
          if ($output -match 'Public signature:\s*(?<sig>\S+)') {
              $newSignature = $Matches['sig']
          } else {
              Write-Error "Could not find public signature in output."
          }
          $tag = "${{ github.ref_name }}"
          $version = $tag -replace '^v', ''
          $latest = @"
          {
            "version": "$version",
            "platforms": {
              "windows-x86_64": {
                "signature": "",
                "url": "https://github.com/flick9000/winscript/releases/download/$tag/winscript-installer.exe"
              },
              "windows-x86_64-nsis": {
                "signature": "",
                "url": "https://github.com/flick9000/winscript/releases/download/$tag/winscript-installer.exe"
              }
            }
          }
          "@
          $modified = $latest -replace '("signature":\s*")[^"]*(")', "`$1$newSignature`$2"
          $modified | Out-File -FilePath "latest.json"
          gh release upload "${{ github.ref_name }}" "latest.json" --clobber
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
